name: Compile and Test Go Program

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Get deps
        run: go mod download

      - name: Build
        run: go build -v -o goSpoof ./cmd/gospoof

      - name: Test
        run: go test ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-bin
          path: |
            coverage.out
            goSpoof
