name: Build & Test GoSpoof

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cmd/gospoof

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: cmd/gospoof/go.mod
          cache: true
          cache-dependency-path: cmd/gospoof/go.sum

      - name: Ensure deps (yaml + tidy)
        run: |
          go get gopkg.in/yaml.v3@v3.0.1
          go mod tidy
          go list -m all

      - name: Build
        run: go build -v -o goSpoof .

      - name: Test
        run: go test ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: goSpoof-${{ github.sha }}
          path: |
            ${{ github.workspace }}/cmd/gospoof/goSpoof
            ${{ github.workspace }}/cmd/gospoof/coverage.out
