name: Compile and Test Go Program

on:
  schedule:
    - cron: "0 9 * * *"   
  workflow_dispatch:        

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod
          cache: true

      - name: Get deps
        working-directory: ./src
        run: go mod download

      - name: Build
        working-directory: ./src
        run: go build -v -o goSpoof

      - name: Test
        working-directory: ./src
        run: go test ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-bin
          path: |
            src/coverage.out
            src/goSpoof
