name: Compile and Test Go Program

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.0'

      - name: Compile Go program
        run: go build
        working-directory: ./src

      - name: push update
        run: |
         git add goSpoof
         git commit -m "adding binary"
         git push origin main
             
